layout_spectrum: 0.02002914
color:
  saturation: 0.5058984
  lightness: 0.8046595
  brandStrength: 0.874661
  brandColors:
    - '#EAEAEA'
    - '#383838'
    - '#999999'
  rhythmicContrast: 0.6559139
typography_spectrum: 0.6290323
name: Invasion studio
